- name:  Create EC2 instance
  hosts: localhost
  connection: local
  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance: 
        key_name: "u1"
        instance_type: "t2.micro"
        image_id: "ami-007855ac798b5175e"
        region: "us-east-1"
        security_group: "sg-01df0e5bf87945e46"
        tags:
          Name: "ansibleInstance"
        wait: true
        vpc_subnet_id: "subnet-08ed1142654c50c57"
        network:
          assign_public_id: true
      register: ec2
